version: '2.1'

services:
  task-api-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  task-api:
    image: kristof/task-api
    depends_on:
      - task-api-mongodb
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - TASK_API_MONGO_HOST=task-api-mongodb
      - TASK_API_MONGO_PORT=27017