
spring:
  application:
    name: task-api
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: task-api
      repostitories:
        enabled: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true


---

spring:
  profiles: container
