
spring:
  application:
    name: task-api
  data:
    mongodb:
      host: ${TASK_API_MONGO_HOST:192.168.99.100}
      port: ${TASK_API_MONGO_PORT:27017}
      database: task-api
      repostitories:
        enabled: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true


---

spring:
  profiles: container
